version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ciberdevs_backend_api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - DB_SSL=true
